source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 3.1'

gem 'bundler-audit' # Check dependencies vulnerabilities
gem 'puma'
gem 'rack'
gem 'rack-session'
gem 'rackup'
gem 'redis-namespace'
gem 'securerandom'
gem 'sidekiq'
gem 'sidekiq-cron'
gem 'sidekiq-failures'
gem 'sidekiq-status'
gem 'tzinfo'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
