# --------------------------------------------------
# DEFAULT NGINX CONFIG
#   Don't test when tagging
# --------------------------------------------------
.nginx:
  image: $CONTAINER_TEST_IMAGE
  extends: .rules_common
  variables:
    CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_REF_SLUG
  before_script:
    - mkdir -p $HOME/.docker
    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
    - cd nginx

# --------------------------------------------------
# BUILD STAGE
# --------------------------------------------------
build:nginx:
  stage: build
  image: $CI_REGISTRY/softier/commons/docker:latest
  # rules:
  #   - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
  #     when: never
  extends: .nginx
  script:
    - docker --version
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --target test --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

# --------------------------------------------------
# TEST STAGE
# --------------------------------------------------
test:nginx:
  stage: test
  extends: .nginx
  needs: ['build:nginx']
  allow_failure: true
  script:
    - cat /etc/nginx/nginx.conf
    - nginx -T
