.rules_common:
  rules:
    # Skip when tagging version
    - if: $CI_COMMIT_TAG
      when: never
    # Skip when pushing comes from gitlab api (ex. changelog)
    - if: $CI_PIPELINE_SOURCE == 'api'
      when: never
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
    - if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "production" || $CI_COMMIT_BRANCH =~ /^feature/)
