require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  # EnabledByDefault: true
  NewCops: enable
  TargetRubyVersion: 3.0
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  # DisabledByDefault: true
  Exclude:
  #   - '**/tmp/**/*'
  #   - '**/templates/**/*'
  #   - '**/vendor/**/*'
  #   - 'config/puma.rb'
    - 'lib/tasks/auto_annotate_models.rake'
    # - 'spec/**/**/*'
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - 'config/**/*'
    - 'config.ru'
    - 'bin/**'
    - 'db/**/*'

#################### Layouts ###########################
Layout/HashAlignment:
  EnforcedColonStyle: table

#################### Metrics ###########################
Metrics/PerceivedComplexity:
  Exclude:
    - 'app/models/concerns/search_concern.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/concerns/search_concern.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/api/uploads_controller.rb'
    - 'app/sidekiq/fa5_request/generate_deliveries_job.rb'
    - 'app/models/concerns/search_concern.rb'
    - 'db/**/*'

Metrics/BlockLength:
  Exclude:
    - 'app/models/concerns/search_concern.rb'
    - 'db/**/*'
    - 'spec/**/*'
    - 'lib/tasks/*'
    - 'config/routes.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/models/concerns/search_concern.rb'
    - 'app/controllers/**/*'
    - 'app/sidekiq/**/*'
    - 'db/**/*'

Layout/LineLength:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'

Performance/RedundantMerge:
  Exclude:
    - 'spec/**/*'

Naming/VariableNumber:
  Exclude:
    - 'db/migrate/20220115102039_create_atoll_frequencies.rb'

Style/Documentation:
  Exclude:
    - 'app/controllers/**/*'
    - 'db/migrate/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/sidekiq/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

