source 'https://rubygems.org'

ruby '3.2.5'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.1.5', '>= 7.1.5.1'

# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '>= 5.0'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", ">= 4.0.1"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[windows jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
# gem "rack-cors"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'brakeman' # Check source code vulnerabilities
  gem 'bundler-audit' # Check dependencies vulnerabilities
  gem 'database_cleaner'
  gem 'debug', platforms: %i[mri windows]
  gem 'factory_bot_rails'
  gem 'fasterer'
  gem 'roo', '~> 2.10'
  gem 'rspec_junit_formatter'
  gem 'rspec-rails'
  gem 'rswag-specs', '~> 2.13.0'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
  gem 'simplecov'
  gem 'simplecov-cobertura'
  gem 'timecop'
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"

  gem 'annotate'
  gem 'error_highlight', '>= 0.4.0', platforms: [:ruby]
  gem 'listen', '~> 3.3'
end

# Custom gems
gem 'active_model_serializers', '~> 0.10.0' # New JSON model serialization for API calls
gem 'bcrypt', '~> 3.1' # Hashed password
gem 'dry-transaction' # Transction management
gem 'faker' # Faker
gem 'jwt' # Json Web Token
gem 'pundit', '~> 2.2' # Authorizations management
gem 'responders' # Responders methods
gem 'rswag-api', '~> 2.14.0' # Rswag api
gem 'rswag-ui', '~> 2.14.0' # Rswag ui
# gem 'sidekiq' # Sidekiq background processing
# gem 'sidekiq-cron' # Sidekiq cron
